# Fast MCMC setting
# JEM
model_s: resnet28x10
model: resnet32x4
model_stu: resnet8x4
act: swish
norm: none
g_steps: 20
step_size: 1
capcitiy: 10000
reinit_freq: 0.05
cls: cls
use_py: True
data_noise: 0.03
batch_size: 64
path_t: save/models/resnet32x4_vanilla/res_epoch_240.pth