model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 100
  latent_dim: 256
  img_size: 32


exp_params: 
  batch_size: 256 # Better to have a square number
  LR: 0.002
  weight_decay: 0.0
  scheduler_gamma: 0.95

# trainer_params:
#   gpus: 1
#   max_nb_epochs: 50
#   max_epochs: 50
gpu: 3
plot_cond: True
path_t: /data/lijingru/EBKD/save/models/resnet32x4_vanilla/ckpt_epoch_240.pth
data_noise: 0.
lr_decay_epochs_ebm: 50,100
short_run: False
joint: True
lamda_cls: 0.1
lamda_kl: 10
model_stu: resnet8x4
joint_training:
  open: True
  alpha: 0.1
  beta: 0.9
  stu_lr: 0.01

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  manual_seed: 1265